### ISSUE TITLE
Create a controller for the Sender GUI

### ISSUE THREAD

**Issue by djbotha** [okay-fine/salmon-cannon#11]
This controller needs to have the following functionality:

- [x] Select a file for transfer (#3)
- [x] Send the file (#12 and #5) 
- [x] Update the GUI with progress regarding the file sending (after we've grabbed info from the server via TCP) (#6)
